services:
  api:
    build: .
    restart: unless-stopped
    depends_on:
      clamav:
        condition: service_healthy
      rspamd:
        condition: service_healthy
    environment:
      - CLAMAV_HOST=clamav
      - RSPAMD_HOST=rspamd
      - EMAIL_ANALYSIS_DIR=/data/email-analysis
      - MAP_CACHE_DIR=/data/maps_cache
      - LOG_DIR=/data/logs

      # Choose to cache map images to reduce Mapbox API requests.
      - CACHE_MAPS=false
      
      # Set data retention period in minutes for analysis files. Value of 0 will save files indefinitely.
      - DATA_RETENTION_MINUTES=10
      - DATA_INDEXING_MINUTES=5

      # Set the maximum allowed upload size in megabytes.
      - MAX_UPLOAD_SIZE_MB=10
      
      # CORS options
      - CORS_ALLOW_ORIGINS=https://sentinel-systems.cc    # NO QUOTES, SEPARATE USING ", "
      - CORS_ALLOW_CREDENTIALS=False                      # Boolean
      - CORS_ALLOW_METHODS=GET, POST                      # NO QUOTES, SEPARATE USING ", "
      - CORS_ALLOW_HEADERS=Options, Content-Type          # NO QUOTES, SEPARATE USING ", "
    volumes:
      - ./email-analysis-data:/data/email-analysis
      - ./maps-cache:/data/maps_cache
      - ./logs:/data/logs
    networks:
      - mailsec
    ports:
      - "8000:8000"
    env_file: .env

  clamav:
    image: clamav/clamav:stable
    restart: always
    volumes:
      - clamav_db:/var/lib/clamav
    networks:
      - mailsec
    expose:
      - 3310
    healthcheck:
      test: ["CMD", "clamdscan", "--version"]
      interval: 30s
      timeout: 10s
      retries: 5

  rspamd:
    image: rspamd/rspamd:latest
    restart: always
    depends_on:
      - redis
    volumes:
      - rspamd_config:/var/lib/rspamd
    networks:
      - mailsec
    expose:
      - 11333
    healthcheck:
      test: ["CMD", "rspamadm", "control", "stat"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - mailsec
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  clamav_db:
  rspamd_config:
  redis_data:

networks:
  mailsec:
